# Generated by Django 4.0.1 on 2022-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_user_id', models.CharField(max_length=255, null=True)),
                ('Student_department', models.CharField(max_length=5, null=True)),
                ('section', models.CharField(max_length=1, null=True)),
                ('period', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=255, null=True)),
                ('section', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
