# Generated by Django 4.0.1 on 2022-04-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
