# Generated by Django 4.0.1 on 2022-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Date',
            field=models.CharField(max_length=10),
        ),
    ]
