# Generated by Django 4.0.1 on 2022-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_attendence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
