# Generated by Django 4.0.1 on 2022-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_attendence_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='img',
            field=models.ImageField(null=True, upload_to='./All_QR_codes'),
        ),
    ]
