# Generated by Django 4.0.1 on 2022-04-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_attendence_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='img',
        ),
    ]
