# Generated by Django 4.0.1 on 2022-04-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('department', models.CharField(default='', max_length=255)),
                ('section', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
